#[derive(Clone, Debug, PartialEq)]
pub enum AST {
    Num(f64),
    Add(Box<AST>, Box<AST>),
    Sub(Box<AST>, Box<AST>),
    Mul(Box<AST>, Box<AST>),
    Div(Box<AST>, Box<AST>),
    Pow(Box<AST>, Box<AST>),
    Gt(Box<AST>, Box<AST>),
    Ge(Box<AST>, Box<AST>),
    Lt(Box<AST>, Box<AST>),
    Le(Box<AST>, Box<AST>),
    Eqq(Box<AST>, Box<AST>),
    Neq(Box<AST>, Box<AST>),
    Var,
    Ans,
    Sin(Box<AST>),
    Cos(Box<AST>),
    Tan(Box<AST>),
    Csc(Box<AST>),
    Sec(Box<AST>),
    Cot(Box<AST>),
    Asin(Box<AST>),
    Acos(Box<AST>),
    Atan(Box<AST>),
    Acsc(Box<AST>),
    Asec(Box<AST>),
    Acot(Box<AST>),
    Sinh(Box<AST>),
    Cosh(Box<AST>),
    Tanh(Box<AST>),
    Csch(Box<AST>),
    Sech(Box<AST>),
    Coth(Box<AST>),
    Asinh(Box<AST>),
    Acosh(Box<AST>),
    Atanh(Box<AST>),
    Log(Box<AST>),
    Log2(Box<AST>),
    Log10(Box<AST>),
    Log1p(Box<AST>),
    Exp(Box<AST>),
    Expm1(Box<AST>),
    Sqrt(Box<AST>),
    Cbrt(Box<AST>),
    Abs(Box<AST>),
    Sign(Box<AST>),
    Floor(Box<AST>),
    Ceil(Box<AST>),
    Round(Box<AST>),
    Gamma(Box<AST>),
    Erf(Box<AST>),
    Conj(Box<AST>),
    Re(Box<AST>),
    Im(Box<AST>),
    Pi,
    E,
    Tau,
    Phi,
    I,
}
