name:                 integra
version:              0.4.0.0
visibility:           public
id:                   integra-0.4.0.0-inplace
key:                  integra-0.4.0.0-inplace
license:              MIT
maintainer:           alexanderluo0910@gmail.com
author:               aluoty
category:             Math
abi:                  inplace
exposed:              True
exposed-modules:
    Integra.AST Integra.Evaluator Integra.Numerical Integra.Parser
    Integra.Solver Integra.Special Integra.Token

import-dirs:
    /home/alex/Projects/integra/dist-newstyle/build/x86_64-linux/ghc-9.10.3/integra-0.4.0.0/build

library-dirs:
    /home/alex/Projects/integra/dist-newstyle/build/x86_64-linux/ghc-9.10.3/integra-0.4.0.0/build

library-dirs-static:
    /home/alex/Projects/integra/dist-newstyle/build/x86_64-linux/ghc-9.10.3/integra-0.4.0.0/build

dynamic-library-dirs:
    /home/alex/Projects/integra/dist-newstyle/build/x86_64-linux/ghc-9.10.3/integra-0.4.0.0/build

data-dir:             /home/alex/Projects/integra/.
hs-libraries:         HSintegra-0.4.0.0-inplace
depends:              base-4.20.2.0-4d66
haddock-interfaces:
    /home/alex/Projects/integra/dist-newstyle/build/x86_64-linux/ghc-9.10.3/integra-0.4.0.0/doc/html/integra/integra.haddock

haddock-html:
    /home/alex/Projects/integra/dist-newstyle/build/x86_64-linux/ghc-9.10.3/integra-0.4.0.0/doc/html/integra
